services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    # volumes:
    #   - ./backend:/app  
    networks:
      - treatme-network
    dns:
      - 8.8.8.8

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - treatme-network

volumes:
  redis_data:

networks:
  treatme-network:
    driver: bridge