version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helpore-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    volumes:
    command: node dist/app.js

  mongo:
    image: mongo:6.0
    container_name: helpore-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: helpore-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: